version: '3'
services:
  grafana:
    image: grafana/grafana:9.5.9
    container_name: grafana
    user: "1000"
    volumes:
      - ./data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 192.168.25.105

networks:
  containers:
    external: true
